[supabase]
url = "https://eimpoqkjhxbeoozdzaqx.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpbXBvcWtqaHhiZW9vemR6YXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMDc1ODMsImV4cCI6MjA3NzU4MzU4M30.odTEybClI3tjysEGp2zvz8jpQ_4fMS-Ok-DthPte7pw"
